[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]

[profile.test_v6]
auto_detect_solc = true
src = "test_v6"
out = "out"
libs = ["lib_v6", "lib"]

[profile.test_v4]
auto_detect_solc = true
src = "test_v4"
out = "out"
libs = ["lib_v4", "lib"]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config